###jetty
server:
   port: 7999
   contextPath: /penetrate
##   ssl:
##     key-store: classpath:www-kisme-org.jks
##     key-password: ENC(+r7LBLwX7duNyPs4wSgkhTOHbyaWD8Ii)
##     key-store-password: ENC(+r7LBLwX7duNyPs4wSgkhTOHbyaWD8Ii)

jasypt:
  encryptor:
    password: 666

spring:
   thymeleaf:
     enabled: true
     cache: false
     check-template: true
     check-template-location: true
     content-type: text/html
     encoding: UTF-8
     prefix: classpath:/templates/
     suffix: .html
     mode: HTML5
   http:
     encoding:
       charset: UTF-8
       enabled: true
       force: true

mybatis:
  #  type-aliases-package: com.weasel.frp.domain.device
    mapper-locations: classpath:mybatis/mappers/*.xml
    config-location: classpath:mybatis/mybatis-config.xml

penetrate:
    domain: tun.gogl.top